### ISSUE TITLE
Conflicting class names

### ISSUE THREAD

**Issue by kyle-williams-1** [theforeman/puppet-certs#200]
Many modules use ::certs as a class name within PuppetForge. Since this certs class pertains to Puppet and Katello specifically, it would be very nice to use a less conflicting base class name.

Some ideas might be:
::puppetcerts (as the module name implies)
::foremancerts

Instead of:
::certs

I'm happy to do the PR for this, but I'd like to know first if it's something that would be considered. Thanks!

**Comment by ekohl** [comment]
Naming is hard. Due to the way we expose this module in our installer, a rename is a big undertaking because we need to update a lot of documentation as well. We have always relied on the namespacing but I'll agree that it's somewhat limited.

Is your issue that it conflicts on your system or that searching on the forge is cluttered?

**Comment by ekohl** [comment]
I'm well aware that this is a very generic name and you're not the first to suggest a rename. Given the scope I'm cautious at this moment.

**Comment by ekohl** [comment]
I don't think we're going to rename this module any time soon, so I'm closing this.
