### ISSUE TITLE
without foreman installer?

### ISSUE THREAD

**Issue by superfantasticawesome** [theforeman/puppet-certs#255]
The only way to wrangle the certs module in any repeatable fashion is through puppet apply, or with the foreman installer. Isn't this kind of an anti-pattern?

Are there any plans for making this actually work as a puppet module and not just a component of foreman installer?

**Comment by ekohl** [comment]
I don't know exactly if this module will be modified or if other modules will gain abilities. Simply because I don't have an exact plan. I would like to be able to support this and we probably need some sort of CA server implementation like we could rely on with PuppetCA. I've been thinking about using certmonger which can talk to multiple backends but I never had the time to properly attempt this.

If you do have thoughts, I'd love to hear them. Also wondering why you couldn't use this as a normal module, as long as you provide it with the certs tarball though some other provisioning method.
